{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Values.service.internalPort -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "name" . }}
  name: {{ template "name" . }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  rules:
{{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
        serviceName: {{ $serviceName }}
        servicePort: {{ $servicePort }}
{{- end -}}
{{- end -}}
