apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
  name: {{ template "name" . }}
spec:
  selector:
    app: {{ template "name" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
