namespace: prod
nodeSelector: {}

revisionHistoryLimit: 10

controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.12.0"
    pullPolicy: IfNotPresent
  terminationGracePeriod: 60
  config:
    enableUnderscoresInHeaders: true
    proxyStreamTimeout: 12000s
  hostNetwork: false
  dnsPolicy: ClusterFirst
  electionID: ingress-controller-leader
  ingressClass: prod
  podLabels: {}
  extraArgs: {}
  extraEnvs: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
    port: 10254
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
    port: 10254
  replicaCount: 3
  resources:
    limits:
      cpu: 2000m
    requests:
      cpu: 50m
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    targetPorts:
      http: 80
    type: NodePort
    nodePorts:
      http: 31000
  stats:
    enabled: true
    service:
      clusterIP: ""
      servicePort: 18080
      type: ClusterIP
  metrics:
    enabled: false

defaultBackend:
  name: default-backend
  image:
    repository: k8s.gcr.io/defaultbackend
    tag: "1.3"
  replicaCount: 1
  limits:
    cpu: 10m
    memory: 20Mi
  requests:
    cpu: 10m
    memory: 20Mi
  service:
    clusterIP: ""
    servicePort: 80
    type: ClusterIP
